# Introdução NumPy:

In [1]:
import numpy as np

## Vetores:

In [2]:
vetor = np.array([3, 8, 5, 12])

print('vetor:', vetor)
print('dimensão:', vetor.shape)

vetor: [ 3  8  5 12]
dimensao: (4,)


## Matrizes:

In [ ]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('matriz:', matriz)
print('dimensão:', matriz.shape)

## Geração de Arrays:

In [7]:
array_3x3_um = np.ones((3, 3))
print('array 3x3 com uns\n', array_3x3_um)

array_2x3x3_zero = np.zeros((2, 3, 3))
print('array 2x3x3 com zeros\n', array_2x3x3_zero)

array_faixa = np.arange(0, 100, 10)
print('array de 0 à 100 de 10 em 10\n', array_faixa)

# np.random.seed(20)
array_4x4_aleatorio = np.random.randint(10, size=(4, 4))
print('array 4x4 aleatorio de 0 à 10\n', array_4x4_aleatorio)

array 3x3 com uns
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
array 2x3x3 com zeros
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
array de 0 à 100 de 10 em 10
 [ 0 10 20 30 40 50 60 70 80 90]
array 4x4 aleatorio de 0 à 10
 [[2 5 8 9]
 [5 7 0 4]
 [5 7 9 6]
 [1 0 8 0]]
